#!/usr/bin/env bash

bspc monitor -d 一 二 三 四 五 六 七 八 九

# Behavior
bspc config border_width          1
bspc config window_gap            12
bspc config split_ratio           0.50

# Mouse
bspc config pointer_modifier      mod4
bspc config pointer_action1       none

# Colors
bspc config focus_follows_pointer true
bspc config active_border_color   "#f0f0f0"
bspc config focused_border_color  "#f0f0f0"
bspc config normal_border_color   "#262626"

# Rules
bspc rule -a *:Floating state=floating # sticky=on
bspc rule -a Zathura state=tiled

# EWW
function launch_eww {
  eww daemon
  eww open bar
}

pgrep eww || launch_eww &

# Spotify dameon
pgrep spotifyd || spotifyd &

# Psuedo swallowing
pgrep bspswallow || $HOME/.config/bspwm/scripts/bspswallow &

# Start sxhkd with bspwm bindings
pgrep -f "sxhkd -c $HOME/.config/bspwm/sxhkdrc" || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# Alttab
pgrep alttab || alttab -w 1 &
